In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
a.ndim

2

In [3]:
b=np.full((3,3),7)
b

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [4]:
c=np.linspace(10,20,30)
c

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [5]:
d=np.random.random((2,2))
d

array([[0.74759034, 0.7287583 ],
       [0.18623019, 0.43737525]])

In [35]:
e=np.array((1,2,3,4))
f=np.array((5,6,7,8))
np.concatenate((e,f),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [21]:
(np.ones(10))*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [27]:
np.arange(10,31)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [28]:
np.arange(10,52,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [31]:
q=np.arange(0,9)

In [34]:
q.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.random.random(1)

array([0.31038408])

In [49]:
np.random.randn(20)

array([-0.10730838, -0.74122407,  1.66587685,  0.23991238, -2.02312963,
       -0.49032152,  0.99334408,  1.37336643, -0.83683828,  0.94957036,
       -0.76460067,  1.95213115,  0.75803596, -0.42575472,  0.1070206 ,
       -0.86235375,  0.91599405, -2.30605336, -1.46239319,  0.36019103])

In [54]:
w=np.linspace(0,1,20)
w

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [55]:
w.ndim

1

In [58]:
np.matrix(np.linspace(0.01,1,100))

matrix([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
         0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ,
         0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ,
         0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ,
         0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ,
         0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ,
         0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ,
         0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ,
         0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ,
         0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [59]:

np.arange(1,101).reshape(10,10) / 100


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [83]:
e=np.arange(1,26).reshape(5,5)
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [84]:
e[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [87]:
e[:2,1:2]

array([[2],
       [7]])

In [88]:
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [93]:
np.sum(e, axis=0)

array([55, 60, 65, 70, 75])

In [94]:
np.sum(e, axis=1)

array([ 15,  40,  65,  90, 115])

In [162]:
car["am"]=1
car

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   1   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   1   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   1   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   1   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   1   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   1   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   1   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   1   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   1   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   1   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   1   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   1   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   1   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   1   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   1   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   1   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   1   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   1   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   1   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [163]:
car['cyl'].sort_values(ascending=False)


16    8
30    8
4     8
28    8
6     8
24    8
23    8
22    8
21    8
11    8
12    8
13    8
14    8
15    8
1     6
29    6
0     6
10    6
9     6
5     6
3     6
17    4
18    4
19    4
20    4
8     4
7     4
25    4
26    4
27    4
2     4
31    4
Name: cyl, dtype: int64

In [184]:
car[(car['cyl']>6) & (car['hp']>300)]


Unnamed: 0   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
30  Maserati Bora  15.0    8  301.0  335  3.54  3.57  14.6   0   1     5     8

In [177]:
car[(car['cyl']>6) & (car['hp']>300)]


Unnamed: 0   mpg  cyl   disp   hp  drat    wt  qsec  vs  am  gear  carb
30  Maserati Bora  15.0    8  301.0  335  3.54  3.57  14.6   0   1     5     8

### Pandas

In [11]:
import pandas as pd
car=pd.read_csv("C:/Users/Nikhil/Downloads/mtcars.csv")
car

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [120]:
car.head(5)

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [122]:
car.head(10)

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
5            Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
6         Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3   
7          Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
8           Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
9           Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2  
5     1  
6     4  
7     2  
8     2  
9     4

In [12]:
car['mpg']

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [161]:
car.iloc[0:1,1:8]

mpg  cyl   disp   hp  drat    wt   qsec
0  21.0    6  160.0  110   3.9  2.62  16.46

In [159]:
car.loc[:,'mpg':'qsec']


mpg  cyl   disp   hp  drat     wt   qsec
0   21.0    6  160.0  110  3.90  2.620  16.46
1   21.0    6  160.0  110  3.90  2.875  17.02
2   22.8    4  108.0   93  3.85  2.320  18.61
3   21.4    6  258.0  110  3.08  3.215  19.44
4   18.7    8  360.0  175  3.15  3.440  17.02
5   18.1    6  225.0  105  2.76  3.460  20.22
6   14.3    8  360.0  245  3.21  3.570  15.84
7   24.4    4  146.7   62  3.69  3.190  20.00
8   22.8    4  140.8   95  3.92  3.150  22.90
9   19.2    6  167.6  123  3.92  3.440  18.30
10  17.8    6  167.6  123  3.92  3.440  18.90
11  16.4    8  275.8  180  3.07  4.070  17.40
12  17.3    8  275.8  180  3.07  3.730  17.60
13  15.2    8  275.8  180  3.07  3.780  18.00
14  10.4    8  472.0  205  2.93  5.250  17.98
15  10.4    8  460.0  215  3.00  5.424  17.82
16  14.7    8  440.0  230  3.23  5.345  17.42
17  32.4    4   78.7   66  4.08  2.200  19.47
18  30.4    4   75.7   52  4.93  1.615  18.52
19  33.9    4   71.1   65  4.22  1.835  19.90
20  21.5    4  120.1   97  3.70  2.465  20.01
21  15.5    8  318.0  150  2.76  3.520  16.87
22  15.2    8  304.0  150  3.15  3.435  17.30
23  13.3    8  350.0  245  3.73  3.840  15.41
24  19.2    8  400.0  175  3.08  3.845  17.05
25  27.3    4   79.0   66  4.08  1.935  18.90
26  26.0    4  120.3   91  4.43  2.140  16.70
27  30.4    4   95.1  113  3.77  1.513  16.90
28  15.8    8  351.0  264  4.22  3.170  14.50
29  19.7    6  145.0  175  3.62  2.770  15.50
30  15.0    8  301.0  335  3.54  3.570  14.60
31  21.4    4  121.0  109  4.11  2.780  18.60

In [121]:
car.tail(5)

Unnamed: 0   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4   

    carb  
27     2  
28     4  
29     6  
30     8  
31     2

In [ ]:
car.drop(car['carb'],axis=1, inplace=True)

In [20]:
car

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  
0      4  
1      4  
2      4  
3      3  
4      3  
5      3  
6      3  
7      4  
8      4  
9      4  
10     4  
11     3  
12     3  
13     3  
14     3  
15     3  
16     3  
17     4  
18     4  
19     4  
20     3  
21     3  
22     3  
23     3  
24     3  
25     4  
26     5  
27     5  
28     5  
29     5  
30     5  
31     4

In [21]:
car.isnull().sum()

Unnamed: 0    0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          0
vs            0
am            0
gear          0
dtype: int64

In [22]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  32 non-null     object 
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64  
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64  
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64  
 9   am          32 non-null     int64  
 10  gear        32 non-null     int64  
dtypes: float64(5), int64(5), object(1)
memory usage: 2.7+ KB


In [23]:
car.iloc[:,4]


0     110
1     110
2      93
3     110
4     175
5     105
6     245
7      62
8      95
9     123
10    123
11    180
12    180
13    180
14    205
15    215
16    230
17     66
18     52
19     65
20     97
21    150
22    150
23    245
24    175
25     66
26     91
27    113
28    264
29    175
30    335
31    109
Name: hp, dtype: int64

In [24]:
car.iloc[7:,4:]

hp  drat     wt   qsec  vs  am  gear
7    62  3.69  3.190  20.00   1   0     4
8    95  3.92  3.150  22.90   1   0     4
9   123  3.92  3.440  18.30   1   0     4
10  123  3.92  3.440  18.90   1   0     4
11  180  3.07  4.070  17.40   0   0     3
12  180  3.07  3.730  17.60   0   0     3
13  180  3.07  3.780  18.00   0   0     3
14  205  2.93  5.250  17.98   0   0     3
15  215  3.00  5.424  17.82   0   0     3
16  230  3.23  5.345  17.42   0   0     3
17   66  4.08  2.200  19.47   1   1     4
18   52  4.93  1.615  18.52   1   1     4
19   65  4.22  1.835  19.90   1   1     4
20   97  3.70  2.465  20.01   1   0     3
21  150  2.76  3.520  16.87   0   0     3
22  150  3.15  3.435  17.30   0   0     3
23  245  3.73  3.840  15.41   0   0     3
24  175  3.08  3.845  17.05   0   0     3
25   66  4.08  1.935  18.90   1   1     4
26   91  4.43  2.140  16.70   0   1     5
27  113  3.77  1.513  16.90   1   1     5
28  264  4.22  3.170  14.50   0   1     5
29  175  3.62  2.770  15.50   0   1     5
30  335  3.54  3.570  14.60   0   1     5
31  109  4.11  2.780  18.60   1   1     4

In [39]:
df=(1,2,3,4,5,6,7,8,9,0)
a=pd.Series(df,index=['a','b','c','d','e','f','g','h','i','j'])
a

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
j    0
dtype: int64

In [116]:
dict={"A":["5"], "B":["9"]}
type(dict)

dict

In [118]:
df1_df=pd.DataFrame(dict)
df1_df

A  B
0  5  9